#!/bin/bash - 
#===============================================================================
#
# 
#         USAGE: ./push.sh 
#        AUTHOR: liuxueyang (lxy), liuxueyang457@163.com
#  ORGANIZATION: Hunan University
#       CREATED: 04/11/2014 19:31
#===============================================================================

set -o nounset                              # Treat unset variables as an error

status=$(git status | grep 'nothing to commit')
if [ "$status" == "" ]; then
	git add --all 
	git commit -m 'add or modify sth.'
	git push origin master
fi

exit 0
